Fix M1 Docker Emulation
ethyca/fides pull request #1286
Opened 2022-10-08 04:25 UTC by ThomasLaPiana

Closes #1051
Closes #936 

### Code Changes

* [ ] _list your code changes here_

### Steps to Confirm

* [ ] _list any manual steps taken to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  * [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

_Write some things here about the changes and any potential caveats_

2022-10-08 04:39 UTC, ThomasLaPiana commented
I don't really have a way to test this, but I'm thinking we might also need a platform check here for the mssql portions

2022-10-08 04:54 UTC, ThomasLaPiana commented
note here from slack that on M1 machines they come up as `arm64`, vs. `amd64` for x86 architecture

2022-10-08 05:06 UTC, ThomasLaPiana commented
figured out that I could test by forcing emulation for arm, now trying to figure out how to skip installing pyodbc

2022-10-08 09:01 UTC, ThomasLaPiana commented
all currently failing tests are expected/known occasionally failing

2022-10-08 12:05 UTC, sanders41 commented
First off in testing this is SOOOO much better 🚀 

Previous build times: ~ 20-30 minutes
Build time now with no cache: ~ 2 minutes

Testing in the container:
Previously ~ 3 minutes for test collection
Test collection now ~ 20 seconds

In testing I'm seeing a lot of test failures that don't seem related to this change, and I don't know why they fail now but didn't before. One thing I have seen is in the unit test nox command it has `-m "not integration and not integration_external and not integration_saas"` and I am having tests with `@pytest.mark.external` fail. So our mark should at least be `-m "not integration and not integration_external and not integration_saas and not external"`. The current mark is what it has always been so I don't know why it worked previously and not here.

Would you rather work on fixing these issues in this PR, or create a separate issue to fix this and any new ones like it that come up?

2022-10-10 13:32 UTC, sanders41 requested changes
I am getting some errors on the ops integration tests because the mssql driver isn't installed.

At startup of the testings I get

```console
Traceback (most recent call last):
  File "/fides/tests/ops/integration_tests/setup_scripts/mssql_setup.py", line 39, in <module>
    mssql_setup()
  File "/fides/tests/ops/integration_tests/setup_scripts/mssql_setup.py", line 16, in mssql_setup
    engine = sqlalchemy.create_engine(MASTER_MSSQL_URL)
  File "<string>", line 2, in create_engine
  File "/root/.local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 560, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/root/.local/lib/python3.10/site-packages/sqlalchemy/connectors/pyodbc.py", line 43, in dbapi
    return __import__("pyodbc")
ModuleNotFoundError: No module named 'pyodbc'
```

For this one what I am thinking we could to is change [this line](https://github.com/ethyca/fides/blob/763d605b577cb6b813d258e9f3550c04af67ae99/tests/ops/integration_tests/setup_scripts/mssql_setup.py#L39) to

```py
    try:
        mssql_setup()
    except ModuleNotFoundError:
        print("MS SQL drivers not installed, skipping setup")
```

I also get errors on the integration tests that interact with MS SQL. 

```console
FAILED tests/ops/integration_tests/test_connection_configuration_integration.py::TestMicrosoftSQLServerConnection::test_mssql_db_connection_connect_with_components
FAILED tests/ops/integration_tests/test_connection_configuration_integration.py::TestMicrosoftSQLServerConnection::test_mssql_db_connection_connect_with_url
FAILED tests/ops/integration_tests/test_connection_configuration_integration.py::TestMicrosoftSQLServerConnection::test_connection_configuration_test
FAILED tests/ops/integration_tests/test_connection_configuration_integration.py::TestMicrosoftSQLServerConnection::test_mssql_db_connector - ModuleNotF...
ERROR tests/ops/integration_tests/test_integration_mssql_example.py::test_mssql_example_data - ModuleNotFoundError: No module named 'pyodbc'
ERROR tests/ops/integration_tests/test_sql_task.py::test_mssql_access_request_task - ModuleNotFoundError: No module named 'pyodbc'
ERROR tests/ops/service/privacy_request/request_runner_service_test.py::test_create_and_process_access_request_mssql - ModuleNotFoundError: No module n...
ERROR tests/ops/service/privacy_request/request_runner_service_test.py::test_create_and_process_erasure_request_specific_category_mssql - ModuleNotFoun...
```

Maybe for these we could mark them as `dangerous-integration` rather than `integration` or something like that?

2022-10-10 13:32 UTC, sanders41 commented on docs/fides/docs/development/overview.md
> +1. The next best way to work on Fides is by utilizing the `Noxfile` commands:
```suggestion
1. The recommended way to work on Fides is by utilizing the `Noxfile` commands:
```

2022-10-11 02:55 UTC, ThomasLaPiana commented
Good finds, I agree we'll need some conditional import checking and that looks like the spot to do it!

As for the tests, I'd be ok to add/update that mark, or we can skip the `integration_mssql` ones specifically for now

2022-10-11 11:40 UTC, sanders41 commented
> As for the tests, I'd be ok to add/update that mark, or we can skip the integration_mssql ones specifically for now

Skipping mssql works also, they are the only ones causing issues.

2022-10-12 03:25 UTC, ThomasLaPiana commented
@sanders41 so the solution I decided on here was to add an option to force which platform to build for, instead of splitting out the tests specifically. This allows users to force the platform and run everything as it would in CI.

For local development, I felt that people would be running tests in a more targeted fashion from within their shell, and that the MSSQL tests are such a small fraction of the overall test coverage that this wouldn't be a major hindrance.

This is compounded by the fact that `run_infrastructure` is the one performing all of the docker-level setup (instead of pytest itself, which I think should be the one responsible), so filtering MSSQL out of the rest of the pytest marks and setting it up separately is in and of itself large enough to be its own ticket.

2022-10-12 04:24 UTC, ThomasLaPiana commented
i confirmed that all tests can be collected without issue for both `ctl` and `ops` using the emulated dockerfile

2022-10-12 04:36 UTC, ThomasLaPiana commented
errors here seem to be unrelated to code changes (external mailchimp test failing)

2022-10-12 10:59 UTC, sanders41 approved these changes
I agree on all points. I would love to get the run infrastructure into pytest.

It also looks to me like these test failures aren't related to this PR so approving.

2022-10-12 13:19 UTC, merged

2022-10-12 13:34 UTC, ThomasLaPiana commented
appreciate the review @sanders41 I know this was a heavy one!