Refactor CI workflows to leverage matrixes for less code duplication
ethyca/fides pull request #1702
Opened 2022-11-07 04:29 UTC by ThomasLaPiana

Closes #1701 

### Code Changes

* [ ] update the static checks to use a matrix

### Steps to Confirm

* [ ] _list any manual steps taken to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  * [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

There is a lot of unnecessary code duplication in our CI jobs, mostly repetitive setup steps where the only thing changing is the final command. This can be done in a smarter way via usage of matrixes

2022-11-07 14:01 UTC, sanders41 requested changes

2022-11-07 14:08 UTC, ThomasLaPiana commented on .github/workflows/backend_checks.yml
> +        # Not all jobs need to run against the Python matrix
@sanders41 they're tests/checks that are unrelated to Python version, as they are testing some part of the application/build that we control and always run consistently ourselves, nothing here is user-facing (i.e. our own docs builds, our own fides annotations, etc.)

2022-11-07 14:09 UTC, ThomasLaPiana commented on .github/workflows/backend_checks.yml
> +        - "pytest_ctl(not-external)"
good call, should be consistent. Guess my formatter isn't working!

2022-11-07 14:10 UTC, ThomasLaPiana commented
@sanders41 thanks for the early review comments! good suggestions

2022-11-08 09:43 UTC, ThomasLaPiana commented
Current failures are unrelated:

Ctl tests are fixed in #1700 
Ops tests are due to Shopify API limits, and are unrelated as well #1714

2022-11-08 09:44 UTC, ThomasLaPiana commented
Current failures are unrelated:

Ctl tests are fixed in #1700 
Ops tests are due to Shopify API limits, and are unrelated as well #1714

2022-11-08 16:39 UTC, merged