Expire OTP tokens after a configurable threshold
ethyca/fides pull request #1734
Opened 2022-11-10 20:02 UTC by seanpreston

### Code Changes

* [x] Stores an `attempt_count` alongside the verification code for a consent request
* [x] Increments the `attempt_count` each time a verification attempt is made
* [x] Compares `attempt_count` to the `CONFIG.security.identity_verification_attempt_limit` var at verification time
* [x] If the code is correct, allow
* [x] If incorrect, disallow
* [x] When `attempt_count` is reached, or verification succeeds, remove verification code from the cache so it can't be used again

### Steps to Confirm

* [ ] `nox -s test_env`
* [ ] navigate to the privacy centre, and begin a consent request
* [ ] send an invalid verification code to `/api/v1/consent-request/{consent_request_id}/verify` three times
* [ ] send the valid verification code to `/api/v1/consent-request/{consent_request_id}/verify` once, and confirm the request fails

The consent request verification data is in the format
```
{
  "code": "12345",
  "identity": {"email": "user@example.com"},
  "consent": [{"data_use": "email", "opt_in": True}],
}
```

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  * [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

This change stops bad actors from brute force attacking the consent request endpoint until they successfully guess the verification code and falsely add consent preferences.

2022-11-10 21:00 UTC, seanpreston commented on pyproject.toml
> +max-module-lines="1500"
This seemed like a reasonable level — I'll be adding the same fix for privacy request verification in a subsequent PR. It's also likely worth moving the `ConsentRequest` code into its own module, for the sake of getting this back down to the default of 1000, but I'd rather do that afterwards as clean-up to get this fix out.

2022-11-10 22:53 UTC, pattisdr approved these changes
Logic looks good to me @seanpreston, but I haven't been able to test the flow end-to-end -

2022-11-10 23:43 UTC, pattisdr requested changes
OK got email config setup.
Verified the workflow through the API - that is working well.   I'm running into issues with the privacy center - 

1. Set up email service locally (also had to hardcode CONFIG.notifications.notificiation_service_type to mailgun)
2. Go to privacy center
3. Enter your email into Manage your Consent box
4. Click continue 
5. Get six digit code from email
6. Return to privacy center, enter verification code
7. Observe privacy center make 5 requests: 
   - OPTIONS http://localhost:8080/api/v1/consent-request/<con_id>/verify 200 OK
   - POST http://localhost:8080/api/v1/consent-request/<con_id>/verify 200 OK
   - GET http://localhost:8080/api/v1/id-verification/config 200 OK
   - ANOTHER POST http://localhost:8080/api/v1/consent-request/<con_id>/verify 400 OK
   - Another GET http://localhost:8080/api/v1/id-verification/config/ 200 OK

Now that the verification code is being purged on that first successful POST, it's failing on the second and we can't retrieve the preferences. 

![Screen Shot 2022-11-10 at 5 44 51 PM](https://user-images.githubusercontent.com/9755598/201229280-e0b65319-f959-4e2e-9cb3-007be6d55a8f.png)

2022-11-10 23:47 UTC, seanpreston commented
> Now that the verification code is being purged on that first successful POST, it's failing on the second and we can't retrieve the preferences.

Great spot — will address.

2022-11-11 03:42 UTC, pattisdr approved these changes

2022-11-11 14:33 UTC, merged