Add ability to use mailgun templates
ethyca/fides pull request #2039
Opened 2022-12-14 02:24 UTC by sanders41

Closes #1865

### Code Changes

* Checks if a `fides` mailgun template exists
* If the template exists mailguns emails are sent with the template, if not it falls back to the generic template.

### Steps to Confirm

* [ ] Create a `fides` template in mailgun that contains a `{{{fides_email_body}}}` variable (I can share my api key with whoever tests this that already has this setup).
* [ ] Add the following variable to the `docker-compose.yml`

```
FIDES__EXECUTION__SUBJECT_IDENTITY_VERIFICATION_REQUIRED=true
FIDES__NOTIFICATIONS__NOTIFICATION_SERVICE_TYPE=mailgun
FIDES__NOTIFICATIONS__SEND_REQUEST_COMPLETION_NOTIFICATION=true
FIDES__NOTIFICATIONS__SEND_REQUEST_RECEIPT_NOTIFICATION=true
FIDES__NOTIFICATIONS__SEND_REQUEST_REVIEW_NOTIFICATION=true
```

* [ ] Create a mailgun messaging config.
* [ ] Create a privacy request and verify the identity verification email uses the mailgun template

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  * [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

_Write some things here about the changes and any potential caveats_

2022-12-14 17:29 UTC, sanders41 commented
@conceptualshark this will need some docs updates after it is reviewed. Do we have a process for that in the new docs repo yet? Can I just update docs there as I would have in this repo?

2022-12-14 20:55 UTC, eastandwestwind requested changes

2022-12-14 20:55 UTC, eastandwestwind commented on src/fides/api/ops/service/messaging/message_dispatch_service.py
> +                    ),
Can we decide what to append to `data` if our `template_test` is successful? Just in the effort to reduce some duplicate code

2022-12-14 20:55 UTC, eastandwestwind commented on src/fides/api/ops/service/messaging/message_dispatch_service.py
> +                    ),
e.g. append `template` and `h:X-Mailgun-Variables` if template exists, otherwise append `html`?

2022-12-21 21:36 UTC, eastandwestwind approved these changes

2022-12-21 21:53 UTC, eastandwestwind commented
Leaving a note that I've tested pointing to a mailgun acct with the `fides` template, and confirmed that the template is being used:

<img width="661" alt="Screen Shot 2022-12-21 at 4 52 14 PM" src="https://user-images.githubusercontent.com/7697292/209009091-1039405a-e7f6-4256-a1c3-99fda0a886f3.png">

2022-12-21 22:15 UTC, merged