Contact details required for data map and ropa
ethyca/fides pull request #325
Opened 2022-01-21 16:33 UTC by SteveDMurphy

Closes #321

### Code Changes

* [x] Add a `ContactDetail` class
* [x] Add fields populated with `ContactDetail` to organization, system, and dataset resources
* [x] Create `demo_organization.yml`
* [ ] Identify all places where documentation updates are required or would be helpful
* [ ] Look at creating an export command here (potentially) to ensure data usage makes sense

### Steps to Confirm

* [ ] Validated that the new data is correcly applied to the server

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* [ ] Documentation Updated

### Description Of Changes

First stab based on conversations with Eduardo and Kelly! I still think this needs some time diving in and seeing what other impacts exist and docs make sense to be updated.

2022-01-25 16:48 UTC, ThomasLaPiana commented
@SteveDMurphy taking a look at this later today, thank you!

2022-01-25 16:55 UTC, ThomasLaPiana commented on fidesctl/src/fideslang/models.py
> +    name: str = ""
We should be* encrypting this

2022-01-25 16:56 UTC, ThomasLaPiana requested changes
Overall looks great, but need to be encrypting the contact info in the database

2022-01-25 17:51 UTC, SteveDMurphy commented on fidesctl/src/fideslang/models.py
> +    name: str = ""
Oof, thank you! Can't believe I spaced on adding that 🤦🏽

2022-01-27 05:16 UTC, SteveDMurphy commented on fidesctl/src/fideslang/models.py
> +    name: str = ""
I was finally able to work through the remaining issues I was having, although after looking at `fidesops` it seems like there may be a better way of doing it (or at minimum just stay consistent with them) - let me know what you think @ThomasLaPiana , thanks for the help in reviewing this!

2022-01-27 21:18 UTC, ThomasLaPiana commented on docs/fides/docs/language/resources/organization.md
> +    ...
i would prefer to make these fully valid yaml, as we may want to start automatically validating these are part of our docs build process

2022-01-27 21:29 UTC, ThomasLaPiana commented on fidesctl/src/fideslang/models.py
> +    name: str = ""
this option seems fine to me! we'll eventually get crypto added to fideslib and can pull from there, but I'm happy with this implementation

2022-01-27 21:30 UTC, ThomasLaPiana commented
@SteveDMurphy last thing i can see is we need to update the fides resources! merge main to get up-to-date with those and then go ahead and add the new columns and categories!

2022-01-27 21:31 UTC, ThomasLaPiana requested changes
LGTM! Just need to update the fides resources for the project

2022-01-28 03:24 UTC, SteveDMurphy commented
> LGTM! Just need to update the fides resources for the project

Great catch @ThomasLaPiana! I _think_ I added everything correctly (for now, more to come over the next few issues) and ran the evaluation, but please let me know if anything looks a little wonky. Thanks again!

2022-01-28 16:07 UTC, ThomasLaPiana approved these changes
LGTM!

2022-01-28 16:14 UTC, merged