Use `rollup-plugin-postcss` to bundle the `fides.js` components CSS
ethyca/fides pull request #3431
Opened 2023-06-01 22:18 UTC by NevilleS

Closes #3288 

### Code Changes

* [X] Replace `rollup-plugin-css` with `rollup-plugin-postcss`
* [X] Remove the `dist/fides.css` output everywhere it was used
* [X] Rename `lib/overlay.module.css` -> `components/fides.css`

### Steps to Confirm

* [X] Run a `turbo build` and then open `clients/privacy-center/public/fides-js-components-demo.html` and confirm the CSS is still included: 
<img width="1173" alt="image" src="https://github.com/ethyca/fides/assets/1834295/edefe048-c324-45fa-b892-73b2827f0a6b">

### Pre-Merge Checklist

* [X] All CI Pipelines Succeeded
* Documentation:
  * [X] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [X] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [X] Issue Requirements are Met
* [X] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [X]  For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

### Description Of Changes

This was actually really easy!

The most significant impact is on the bundle size: since this adds the CSS to the `fides.js` bundle inline instead of a separate file, we now add another 2 KB to the bundle size, going from 13.69 KB -> 15.66 KB and triggering our 15KB warning:
```
fides-js:build: src/fides.ts → dist/fides.js...
fides-js:build: ️🚨 WARN: fides.js build is getting large! Gzipped size (15.66 KB) exceeded warning size (15 KB)! If you must, update GZIP_SIZE_* constants in clients/fides-js/rollup.config.mjs
fides-js:build: ┌────────────────────────────────┐
fides-js:build: │                                │
fides-js:build: │   Destination: dist/fides.js   │
fides-js:build: │   Bundle Size:  47.09 KB       │
fides-js:build: │   Minified Size:  47.28 KB     │
fides-js:build: │   Gzipped Size:  15.66 KB      │
fides-js:build: │                                │
fides-js:build: └────────────────────────────────┘
```

2023-06-01 22:48 UTC, NevilleS commented
OK, in my testing of this is works well but _doesn't_ fix the styling issue from our NextJS app:
<img width="923" alt="image" src="https://github.com/ethyca/fides/assets/1834295/dbdf2a4a-c36a-4643-af5d-835ead691e44">

The root cause of that appears to be NextJS stripping things out of the <head> tag, surprisingly: https://github.com/vercel/next.js/issues/11012

I think we need to find a way to play nice with NextJS - either natively (unlikely?) or in the Cookie House specifically.

2023-06-02 13:07 UTC, NevilleS commented
Created https://github.com/ethyca/fides/issues/3437 to track the rendering issue in Cookie House.

2023-06-02 13:28 UTC, NevilleS commented
Used `cssnano` to squeeze another 0.4 KB out of the gzipped size (1.5KB pre-gzip):
```
fides-js:build: ┌────────────────────────────────┐
fides-js:build: │                                │
fides-js:build: │   Destination: dist/fides.js   │
fides-js:build: │   Bundle Size:  45.54 KB       │
fides-js:build: │   Minified Size:  45.4 KB      │
fides-js:build: │   Gzipped Size:  15.27 KB      │
fides-js:build: │                                │
fides-js:build: └────────────────────────────────┘
```

Still above 15K which makes me 😢. I tried a bit of extra optimization like search & replacing the CSS prefix `--fides-consent-overlay` with `--fides-overlay`, which cuts another 0.02 KB gzipped (0.57 KB uncompressed):
```
fides-js:build: ┌────────────────────────────────┐
fides-js:build: │                                │
fides-js:build: │   Destination: dist/fides.js   │
fides-js:build: │   Bundle Size:  44.97 KB       │
fides-js:build: │   Minified Size:  44.84 KB     │
fides-js:build: │   Gzipped Size:  15.25 KB      │
fides-js:build: │                                │
fides-js:build: └────────────────────────────────┘
```

Those kinds of optimizations are pretty ineffective since gzip is much more clever than I am, but I still think we *should* reduce our CSS class names / var names just for comprehensibility. I'll wait for https://github.com/ethyca/fides/pull/3430- and https://github.com/ethyca/fides/pull/3429 to land first because the merge conflicts will be vicious otherwise!

2023-06-02 13:42 UTC, NevilleS commented
Waiting for these two PRs to land before finishing this:
1. https://github.com/ethyca/fides/pull/3429
2. https://github.com/ethyca/fides/pull/3430

This is just to let those (more important!) ones land before I rename CSS files and squeeze out a few more bytes of optimizations 🙃

2023-06-02 13:43 UTC, RobertKeyser approved these changes
Looks good to me.

2023-06-02 14:39 UTC, eastandwestwind requested changes

2023-06-02 14:39 UTC, eastandwestwind commented on clients/fides-js/package.json
>      "rollup-plugin-import-css": "^3.2.1",
we can remove this old plugin

2023-06-02 16:12 UTC, NevilleS commented on clients/fides-js/package.json
>      "rollup-plugin-import-css": "^3.2.1",
Oh odd I thought I did that. Thanks

2023-06-02 20:41 UTC, NevilleS commented on clients/fides-js/package.json
>      "rollup-plugin-import-css": "^3.2.1",
Done

2023-06-02 20:42 UTC, NevilleS commented
Did a few CSS renames to try to squeeze a few more bytes out of the build, not much impact:
```
fides-js:build: ┌────────────────────────────────┐
fides-js:build: │                                │
fides-js:build: │   Destination: dist/fides.js   │
fides-js:build: │   Bundle Size:  46.05 KB       │
fides-js:build: │   Minified Size:  45.91 KB     │
fides-js:build: │   Gzipped Size:  15.52 KB      │
fides-js:build: │                                │
fides-js:build: └────────────────────────────────┘
```

2023-06-02 21:47 UTC, merged