Updated README expansion title
ethyca/fides pull request #356
Opened 2022-02-09 22:25 UTC by iamkelllly

Closes #353 

### Code Changes

* [ ] updated README.md with `<summary>` tag update in step 4
* [ ] updated README.md step 2

### Steps to Confirm

* [ ] read the README for flow and reduced repetition
* [ ] read the README for consistency

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* [ ] Documentation Updated

### Description Of Changes

updating README with feedback from @banagale to reduce repetition and increase readability

2022-02-09 23:40 UTC, banagale requested changes
This is good a few other suggestions:

On line 77, consider:

```
2. Use the <code>evaluate</code> command to test if this project's demo analytics and demo marketing systems are compliant with your privacy policy as code:
```

On line 80, consider:

```
<summary>Run <code>fidesctl evaluate demo_resources/</code></summary>
```

Remove line 83, given other output examples do not include the command line.

2022-03-07 19:00 UTC, ThomasLaPiana commented
@iamkelllly anything I can do to help get this merged?

2022-03-16 12:25 UTC, iamkelllly commented
@banagale re-requested your review here, also ccing @conceptualshark to review as well!

2022-03-16 13:39 UTC, conceptualshark approved these changes
👍 good to go with the suggested edit or not, think these changes definitely help with clarity

2022-03-16 13:39 UTC, conceptualshark commented on README.md
> +      Re-run `fidesctl evaluate demo_resources` which will cause an evaluation failure! This is because your privacy policy has 1 rule that should fail if any system uses contact information for mark
I might simplify/clean up this second sentence a little for clarity - 

Running `fidesctl evaluate demo_resources` now causes an evaluation failure. Your privacy policy's 'Reject Direct Marketing' rule disallows collecting contact information for marketing purposes, and flagged adding this data category and use to your `privacy_declarations`.

2022-03-16 16:51 UTC, merged

2022-03-16 17:02 UTC, iamkelllly commented
Thank you for opening this issue and the readability review @banagale - Looking forward to more contributions from you :)