Add Skip Processing Flag for DSR Execution
ethyca/fides pull request #4047
Opened 2023-09-08 16:13 UTC by pattisdr

Closes https://github.com/ethyca/fidesplus/issues/1059
https://github.com/ethyca/fides/issues/2311

### Description Of Changes

Add a `skip_processing` flag for collections in dataset yaml files. If present, that collection will be omitted from the execution graph when processing a DSR.   **This is for DSR processing only, not consent.**

```yaml
dataset:
  - fides_key: postgres_example_test_dataset
    name: Postgres Example Test Dataset
    description: Example of a Postgres dataset containing a variety of related tables like customers, products, addresses, etc.
    collections:
      - name: address
        fides_meta:
          skip_processing: True
```

For completeness, a similar flag can be added to the saas config at the endpoint level if needed:
```yaml
saas_config:
  fides_key: saas_connector_example
  name: SaaS Example Config
  type: custom
  description: A sample schema representing a SaaS for Fides
  version: 0.0.1

  endpoints:
    - name: skipped_collection
      skip_processing: True
      requests:
        read:
          method: GET
          path: /v1/misc_endpoint/<list_id>
          param_values:
            - name: list_id
              references:
                - dataset: saas_connector_example
                  field: users.list_ids
                  direction: from
```

### Code Changes

* [ ] Fideslang bump needed, adds "skip_processing" Optional boolean under CollectionMeta
* [ ] Updates `convert_dataset_to_graph` which is called with `Dataset.get_graph` to omit collections with `skip_processing` set to True under collection fides meta.  This would be relevant for a yaml file associated with a database.
* [ ] Updates `merge_datasets`, also called by `Dataset.get_graph` which is relevant for Saas configs only.  Combining the saas config and the dataset config into a single graph.  This also removes collections with `skip_processing`. 
* [ ] Modifies `SaaSConfig.get_graph` to pass on the value of `skip_processing` when building the Collection so it can later be used to remove the collection in `merge_datasets`. We don't want to remove the collection at this point, but do this later in `merge_datasets`, as the existence of a skipped collection in the dataset yaml would cause it to be added back in the merge.
* [ ] Fixes an earlier issue where we prevented a graph from being restarted if we didn't have a saved collection and step.  We originally only allowed graphs to be restarted if they failed within the graph.   If there's no saved checkpoint, restart from the beginning.  Added this here so if a DSR fails because customer added "skip_processing" to a collection that was needed, they can make adjustments and then resume from the beginning.

### Steps to Confirm

* [ ] _list any manual steps for reviewers to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

2023-09-08 17:28 UTC, pattisdr commented on requirements.txt
> +fideslang @ git+https://github.com/ethyca/fideslang.git@ee1323ccdeca69c9c80c1d3c1423486cca74ba19#egg=fideslang
This is temporarily pinned here https://github.com/ethyca/fideslang/compare/fidesplus_1059_dsr_flag_1_4_5?expand=1, adding the new "skip_processing" flag to CollectionMeta, but based off of the 1.4.5 tag until the fideslang 2.0 work is merged

2023-09-08 18:40 UTC, pattisdr commented
Ah some tests to address first!

2023-09-08 22:37 UTC, pattisdr commented on requirements.txt
> +fideslang @ git+https://github.com/ethyca/fideslang.git@ee1323ccdeca69c9c80c1d3c1423486cca74ba19#egg=fideslang
Argh okay we just released fideslang 1.4.6 today. I am just going to hold off on getting this PR updated with main for now and wait for the fideslang 2.0 dust to settle hopefully.

2023-09-11 21:25 UTC, galvana requested changes
Nice easy to follow change! I just left some comments around the docstrings and logger statements that might help with troubleshooting in the future

2023-09-12 19:17 UTC, pattisdr commented on src/fides/api/api/v1/endpoints/privacy_request_endpoints.py
>              _process_privacy_request_restart(
good callout!

2023-09-12 19:24 UTC, pattisdr commented on tests/ops/util/test_dataset_yaml.py
> +        """Skipping a collection that shouldn't be skipped is not picked in convert_dataset_to_graph, but
Yes! I don't think we have all the information to necessarily flag this in `convert_dataset_to_graph` as this is just looking at one dataset at a time.  A collection in Dataset A may be referencing a collection in Dataset B, which is not available within that function. But instantiating DatasetGraph has you pass in all the Datasets that are relevant for DSR processing.

I see I have a typo here which makes it read in an odd way, so I'll adjust that.

2023-09-12 19:57 UTC, pattisdr commented on requirements.txt
> +fideslang @ git+https://github.com/ethyca/fideslang.git@ee1323ccdeca69c9c80c1d3c1423486cca74ba19#egg=fideslang
To pull in main and retest I have a new commit based off of 1.4.6 here in the requirements: https://github.com/ethyca/fideslang/pull/163.  This is still temporary until fideslang 2.0 is merged, hopefully tomorrow!

2023-09-12 20:03 UTC, pattisdr commented
I think this is ready for another pass @galvana. Won't be merging until after fideslang 2.0 migration changes are in and I get another fideslang migration released.

2023-09-13 20:39 UTC, pattisdr commented
@galvana the prerequisite fideslang release is out now, ready for a final review, hoping to merge today!

2023-09-13 22:18 UTC, galvana approved these changes
Thanks for making the recommended changes!

2023-09-13 22:21 UTC, pattisdr commented
yay thank you for your review @galvana 🎉 🎉 🎉

2023-09-14 00:25 UTC, merged