update mkdocs-material version (#415)
ethyca/fides pull request #416
Opened 2022-03-25 18:16 UTC by conceptualshark

Closes #415

### Code Changes

* update mkdocs version to be compatible with recent jinja2 release 

### Description Of Changes

Mkdocs pushed [a patch](https://github.com/squidfunk/mkdocs-material/releases/tag/8.2.7) to limit the jinja version range. Updating the pinned version in the docs' `requirements.txt` will resolve the issue for now, but might not be the best strategy for versioning in the future.

2022-03-26 14:57 UTC, ThomasLaPiana commented
@conceptualshark is this ready for review?

If it's ready go ahead and assign reviewers so we make sure it doesn't get forgotten about! If it still needs some work please change it to draft status

Thank you for the fix!

2022-03-28 15:52 UTC, PSalant726 requested changes

2022-03-28 15:52 UTC, PSalant726 commented on docs/fides/docs/schemas/config_schema.json
> +        "analytics_id": "6044ce70af305cf78969a3cd7a5371ba"
Please remove this line. Even though an `analytics_id` is required (for clients that are opted into analytics), this value is associated with a specific instance and should not exist in VCS.

2022-03-28 15:52 UTC, PSalant726 commented on docs/fides/docs/schemas/config_schema.json
> +          "default": "6044ce70af305cf78969a3cd7a5371ba",
This default should be `""`, or removed.

2022-03-28 17:48 UTC, PSalant726 requested changes
To clarify my previous comments, the `analytics_id` and `analytics_opt_out` config options are valid (new) config options. Ideally they wouldn't be removed completely from the schema. It's just the _value_ of the `analytics_id` that needs to be omitted, as it represents a unique instance of fidesctl.

2022-03-28 20:34 UTC, PSalant726 approved these changes

2022-03-28 21:13 UTC, ThomasLaPiana approved these changes
LGTM! Thanks for the fix

2022-03-28 21:14 UTC, merged