Read only consent management table and filters
ethyca/fides pull request #4456
Opened 2023-11-22 22:08 UTC by TheAndrewJackson

Closes #<issue>

### Description Of Changes

_Write some things here about the changes and any potential caveats_

### Code Changes

* [ ] _list your code changes here_

### Steps to Confirm

* [ ] _list any manual steps for reviewers to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

2023-11-27 21:04 UTC, TheAndrewJackson commented on clients/admin-ui/src/features/common/table/v2/PaginationBar.tsx
> +export const PaginationBar = ({
This files diff got a little messed up due to a merge from `main`

2023-11-27 21:06 UTC, TheAndrewJackson commented on clients/admin-ui/src/features/configure-consent/ConfigureConsent.tsx
This file is no longer used

2023-11-27 21:09 UTC, TheAndrewJackson commented on clients/admin-ui/src/features/configure-consent/VendorCookieTable.tsx
> +  // const [systemToEdit, setSystemToEdit] = useState<System | undefined>(
This was to get the build working. This component is effectively deprecated but I'm keeping in the code base just in case

2023-11-27 21:10 UTC, TheAndrewJackson commented on clients/admin-ui/src/features/system/add-multiple-systems/AddMultipleSystems.tsx
> +  } = useClientSidePagination(tableInstance);
This will function that same as before. It's just updating the table to use the new client side pagination hook.

2023-12-01 01:26 UTC, galvana commented
Some of the text needs to be changed to sentence-case (`Data uses`, `Legal bases`, `16 purposes`, `16 data uses` etc.)
![image](https://github.com/ethyca/fides/assets/2092272/11d6d84e-5672-488b-ba0e-0d3b849c7a8f)

Same for the text here (`Reset filters`)
![image](https://github.com/ethyca/fides/assets/2092272/12b874b8-e11c-42a3-83a4-040d8e1cf8bb)

2023-12-01 02:14 UTC, galvana commented
I found a bug with the pagination, it seems like we might just need to reset the current page whenever the filter updates

Steps to reproduce:

1. Add enough systems to be able to paginate (like adding all the vendors)
2. Paginate in a few pages
3. Type into the search box, the pagination details will be incorrect
4. Paginate back and the results will be available in the earlier pages
![image](https://github.com/ethyca/fides/assets/2092272/f601297b-b05f-4456-8904-d58a8a154535)

2023-12-01 02:28 UTC, galvana requested changes
I called out a few places that need sentence-casing but the biggest issue is the pagination bug 🐞. I also started commenting with some style suggestions but I decided to just create another PR so you can review that and pull in whatever you agree with (borrowed the approach from @adamsachs, thanks Adam!)

2023-12-01 15:55 UTC, TheAndrewJackson commented on clients/admin-ui/cypress/e2e/consent-configuration.cy.ts
They were skipped originally because we were removing that page. I updated to work with the new flow now that we're keeping it.

2023-12-01 18:43 UTC, jpople approved these changes
Pagination bug is fixed, looks good to me!

2023-12-01 18:50 UTC, merged