Update privacy notice page to use new table
ethyca/fides pull request #4641
Opened 2024-02-29 16:01 UTC by Kelsey-Ethyca

Closes #[PROD-1455](https://ethyca.atlassian.net/browse/PROD-1455)

### Description Of Changes

_Write some things here about the changes and any potential caveats_

### Code Changes

* [ ] _list your code changes here_

### Steps to Confirm

* [ ] _list any manual steps for reviewers to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

2024-03-04 21:32 UTC, galvana requested changes
This looks good but just make sure to update the import paths to be absolute `~` wherever you added new imports. I usually reference other places where those components are being imported to verify the paths.

2024-03-04 21:32 UTC, galvana commented on clients/admin-ui/src/features/common/table/v2/cells.tsx
> +import { errorToastParams } from "../../toast";
We prefer absolute paths relative to the base directory `~` so we should use
```
../../helpers -> ~/features/common/helpers
../../modals/ConfirmationModal -> ~/features/common/modals/ConfirmationModal
../../toast -> ~/features/common/toast
```
This way the imports will always be accurate even if the components are refactored to be in a different location relative to each other

2024-03-04 21:32 UTC, galvana commented on clients/admin-ui/src/features/privacy-notices/PrivacyNoticesTable.tsx
> +  const inventoryColumns: ColumnDef<LimitedPrivacyNoticeResponseSchema, any>[] =
```suggestion
  const privacyNoticeColumns: ColumnDef<LimitedPrivacyNoticeResponseSchema, any>[] =
```

2024-03-04 22:50 UTC, Kelsey-Ethyca commented on clients/admin-ui/src/features/privacy-notices/PrivacyNoticesTable.tsx
> +  const inventoryColumns: ColumnDef<LimitedPrivacyNoticeResponseSchema, any>[] =
✅

2024-03-05 01:06 UTC, galvana commented
@Kelsey-Ethyca don't forget the change log!

2024-03-05 02:18 UTC, merged