Update privacy notice form
ethyca/fides pull request #4648
Opened 2024-03-01 15:49 UTC by jpople

Closes PROD-1457

### Description Of Changes

Updates privacy notice form and table to work with new endpoints.  Note that the component used for selecting languages here is temporary and should be changed to use the new ScrollableList component-- ticket for that change is [here](https://ethyca.atlassian.net/browse/PROD-1770?atlOrigin=eyJpIjoiOTY5ZjM1Nzc5NTYwNDRmZThlNjY0NmFjNGNmZmQ0MmUiLCJwIjoiaiJ9).

### Code Changes

* [ ] Privacy notice form is reworked to accommodate model changes
* [ ] Add new PrivacyNoticeTranslationForm component
* [ ] Notice endpoints that were previously batch changes have been changed to single notice endpoints with id
* [ ] Privacy notice table has been updated to use the new `limited_update` endpoint that's specific to enable/disable notices

### Steps to Confirm

* [ ] Navigate to `http://localhost:3000/consent/privacy-notices`
* [ ] Add a new privacy notice with translations, save
* [ ] Edit an existing privacy notice, save
* [ ] Add a system with an applicable data use to one of your privacy notices
* [ ] Return to notices table, enable/disable corresponding notice

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

2024-03-01 18:55 UTC, eastandwestwind requested changes
Code looks solid, but had some functional issues while testing the language list. See https://www.loom.com/share/9bbce69d11b3458890b81a0efd21a39b

2024-03-01 18:55 UTC, eastandwestwind commented on clients/admin-ui/src/features/common/Layout.tsx
> +      height={padded ? "calc(100vh - 48px)" : "100vh"}
⭐

2024-03-01 18:55 UTC, eastandwestwind commented on clients/admin-ui/src/features/privacy-notices/PrivacyNoticeForm.tsx
> +      // const { notice_key, ...valuesToSubmit } = values;
can we remove this commented-out code?

2024-03-01 21:55 UTC, eastandwestwind commented
Functionally looking great now, aside from this issue when attempting to enable a notice:

<img width="1139" alt="Screenshot 2024-03-01 at 4 52 30 PM" src="https://github.com/ethyca/fides/assets/7697292/0aeaae94-73a1-4b96-8c0f-50d8bc8cfba0">

2024-03-01 21:58 UTC, eastandwestwind approved these changes

2024-03-04 15:11 UTC, jpople commented
Confirmed with @Kelsey-Ethyca that enable/disable is functioning OK, merging.

2024-03-04 15:12 UTC, merged