Adding ability to delete properties
ethyca/fides pull request #4708
Opened 2024-03-14 18:13 UTC by galvana

Closes [PROD-1664](https://ethyca.atlassian.net/browse/PROD-1664)

### Description Of Changes

Adding the ability to delete properties, only available to owners and contributors. Verifies that all of the experiences on the property are unlinked before being able to delete the property.

### Code Changes

* [ ] Added delete button to property table rows and property edit page
* [ ] Removed the cascade deletes between `plus_property`, `plus_privacy_experience_config_property` to avoid putting the property/privacy_experience_config entries into an invalid state

### Steps to Confirm

* [ ] Start fidesplus off of the branch in https://github.com/ethyca/fidesplus/pull/1353
* [ ] Start the Admin UI in this PR
* [ ] Create a property without privacy experiences
* [ ] Create a property with at least one privacy experience
* [ ] Verify the delete buttons in the rows and edit page are disabled/enabled according to the state of the properties

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* [ ] Issue Requirements are Met
* [ ] Update `CHANGELOG.md`

[PROD-1664]: https://ethyca.atlassian.net/browse/PROD-1664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-03-20 02:58 UTC, Kelsey-Ethyca commented on clients/admin-ui/cypress/e2e/properties.cy.ts
TDD for the win! Lovely!!

2024-03-20 03:45 UTC, Kelsey-Ethyca commented
AC
✅ When a property exists and I view the details of it, then a delete button is shown on the bottom left of the screen.
<img width="1054" alt="Screenshot 2024-03-19 at 8 42 54 PM" src="https://github.com/ethyca/fides/assets/101993653/f28da2b6-ab3a-450b-bc5b-2fd12f576b04">
✅ When a property exists but is NOT referenced by a privacy experience, then I can delete the property.
✅ When a property exists, but is referenced by a privacy experience, then I cannot delete it.
<img width="1430" alt="Screenshot 2024-03-19 at 8 43 40 PM" src="https://github.com/ethyca/fides/assets/101993653/46aa3fcf-27c8-4a66-9dff-b0691c003e36">

Stretch AC
✅ When a property exists that cannot be deleted, then the UI provides a tooltip explaining what to do in order to delete the property.
<img width="1434" alt="Screenshot 2024-03-19 at 8 45 26 PM" src="https://github.com/ethyca/fides/assets/101993653/79cbf0d8-9f40-46ba-a84c-7e976f928881">

2024-03-20 03:54 UTC, Kelsey-Ethyca requested changes
just little nits and questions. UAT passing!

2024-03-20 03:54 UTC, Kelsey-Ethyca commented on clients/admin-ui/src/features/properties/DeletePropertyModalTrigger.tsx
> +import { useDeletePropertyMutation } from "./property.slice";
```suggestion
import { getErrorMessage, isErrorResult } from "~/features/common/helpers";
import { PROPERTIES_ROUTE } from "~/features/common/nav/v2/routes";
import Restrict from "~/features/common/Restrict";
import { errorToastParams, successToastParams } from "~/features/common/toast";
import { useDeletePropertyMutation } from "~/features/properties/property.slice";
```

2024-03-20 03:54 UTC, Kelsey-Ethyca commented on clients/admin-ui/src/features/properties/DeletePropertyModalTrigger.tsx
> +const DeletePropertyModalTrigger: React.FC<Props> = ({
Thoughts on just calling this DeletePropertyModalTrigger?

2024-03-20 03:54 UTC, Kelsey-Ethyca commented on clients/admin-ui/src/features/properties/DeletePropertyModalTrigger.tsx
> +            proceed?
```suggestion
            You are about to delete property {property.name}. This action is not
            reversible. Are you sure you want to
            proceed?
```

2024-03-20 19:39 UTC, galvana reviewed
Thanks for the review @Kelsey-Ethyca! I made the changes you recommended and fixed the CI/CD issues. Ready for round 2!

2024-03-21 04:00 UTC, Kelsey-Ethyca approved these changes

2024-03-21 17:13 UTC, merged