Add showNewExperience fides.js option
ethyca/fides pull request #4810
Opened 2024-04-17 17:20 UTC by Kelsey-Ethyca

Closes #<issue>

### Description Of Changes

_Write some things here about the changes and any potential caveats_

### Code Changes

* [ ] _list your code changes here_

### Steps to Confirm

* [ ] _list any manual steps for reviewers to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

2024-04-18 13:20 UTC, Kelsey-Ethyca commented
UAT https://www.loom.com/share/6d8850e55da242ac958fc26a3ff0910d?sid=f2e37ecd-b757-454b-a98d-988ef192a20e

2024-04-18 22:20 UTC, galvana commented on clients/privacy-center/app/server-environment.ts
> +        ? process.env.FIDES_PRIVACY_CENTER__FIDES_PRIMARY_COLOR === "true"
```suggestion
        ? process.env.FIDES_CLEAR_COOKIE === "true"
```

2024-04-18 22:35 UTC, galvana commented on clients/privacy-center/app/server-environment.ts
> +        : false,
The environment variable name should be `FIDES_PRIVACY_CENTER__FIDES_CLEAR_COOKIE` to match the current convention
```suggestion
      FIDES_CLEAR_COOKIE: process.env.FIDES_PRIVACY_CENTER__FIDES_CLEAR_COOKIE
        ? process.env.FIDES_PRIVACY_CENTER__FIDES_CLEAR_COOKIE === "true"
        : false,
```

2024-04-18 22:37 UTC, galvana requested changes
All the tests passed for the query param use cases but there's an issue loading the env variable, I left an inline comment.

2024-04-18 23:25 UTC, galvana commented on CHANGELOG.md
> +- Added CMP API fidesCleanCookie to load CMP without preferences on refresh [#4810](https://github.com/ethyca/fides/pull/4810)
```suggestion
- Added CMP API fidesClearCookie to load CMP without preferences on refresh [#4810](https://github.com/ethyca/fides/pull/4810)
```

2024-04-19 17:37 UTC, galvana approved these changes
Thanks for making the changes, approved! ✅

2024-04-21 18:53 UTC, merged

2024-04-21 20:08 UTC, NevilleS commented on clients/fides-js/src/docs/fides-options.ts
> +   * When `true`, shows fides.js overlay UI on load. This deletes the fides_consent cookie as if no preferences have been saved on reload.
nit: This isn't actually accurate though, right? This won't force anything to be shown - it only clears the cookie. There will still be no UI shown if the location doesn't match, `fides_disable_banner` is true, etc.

Anyways, I updated the language here: https://github.com/ethyca/fides/pull/4816/files#diff-f3ea8ea74e0a542fd60a2896722c8e25e63153ebccafacbdc6ae0484d3d95b8aR57