Use CheckboxTree for data map filtering
ethyca/fides pull request #4864
Opened 2024-05-04 00:07 UTC by gilluminate

Closes [PROD-1916](https://ethyca.atlassian.net/browse/PROD-1916)

### Description Of Changes

Update the filters on the table to apply a modified version of the hierarchy component that we are using on the dataset page. 

### Code Changes

* [ ] _list your code changes here_

### Steps to Confirm

* [ ] _list any manual steps for reviewers to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

2024-05-07 21:58 UTC, eastandwestwind requested changes
Tested this, and it works great! Couple small requests below.

Also here's some things I've noticed that I'm unsure if caused by this PR, but would like to double check:

1. The vertical spacing between items within the accordions seems uneven:

<img width="440" alt="Screenshot 2024-05-07 at 5 45 20 PM" src="https://github.com/ethyca/fides/assets/7697292/3534f92c-ded5-4402-a97d-2b4785eb4d2a">

2. The `group_by` query param seems to have some encoding issues in the resulting API call:
<img width="1094" alt="Screenshot 2024-05-07 at 5 49 43 PM" src="https://github.com/ethyca/fides/assets/7697292/cba6dc33-2e53-4ee3-8dac-be0df97b0ece">

Let me know and let's re-ticket items as needed!

2024-05-07 21:58 UTC, eastandwestwind commented on clients/admin-ui/src/features/common/utils.ts
> +  strings: string[],
can we re-name `strings` to something more specific, and also add a docstring to this fn?

2024-05-07 22:31 UTC, gilluminate commented
> 1. The vertical spacing between items within the accordions seems uneven:

I think that was existing, but it's an easy fix. Great catch.

2024-05-07 22:32 UTC, gilluminate commented
> 2. The `group_by` query param seems to have some encoding issues in the resulting API call:

That's also existing behavior, and I'm worried about breaking it for the backend. Might be best to re-ticket that one as you suggested.

2024-05-08 11:48 UTC, eastandwestwind approved these changes
Thanks for making those changes! 

Mind creating a new ticket for the query param formatting?

2024-05-08 15:02 UTC, merged