Fix shoppify masking
ethyca/fides pull request #5282
Opened 2024-09-12 13:39 UTC by Vagoasdf

Closes #<issue>

### Description Of Changes

_Write some things here about the changes and any potential caveats_

### Code Changes

* [ ] _list your code changes here_

### Steps to Confirm

* [ ] _list any manual steps for reviewers to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
  * [ ] if there are any new client scopes created as part of the pull request, remember to update public-facing documentation that references our scope registry
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated
* If there are any database migrations:
  * [ ] Ensure that your downrev is up to date with the latest revision on `main`
  * [ ] Ensure that your `downgrade()` migration is correct and works
    * [ ] If a downgrade migration is not possible for this change, please call this out in the PR description!

2024-09-24 13:06 UTC, Vagoasdf commented on tests/ops/integration_tests/saas/test_shopify_task.py
> -        f"{dataset_name}:customer_addresses": 1,
Since we're adding a new address at shipping address, this increases by 1

2024-09-25 01:26 UTC, galvana requested changes
This looks good! Just make sure to bump the version on the `shopify_config.yml` so any existing datasets auto-update. For example `version: 0.0.4` -> `version: 0.0.5`

2024-09-25 01:26 UTC, galvana commented on CHANGELOG.md
> +- Updated Shopify Datamap in order to ignore country and province values that are required on the erasure API
```suggestion
- Updated Shopify dataset in order to flag country, province, and other location values as read-only
```

2024-09-25 17:57 UTC, galvana approved these changes

2024-09-26 13:29 UTC, merged