HJ-116 - Fix BigQuery `partitioning` queries to properly support multiple identity clauses
ethyca/fides pull request #5432
Opened 2024-10-29 16:44 UTC by andres-torres-marroquin

Fix BigQuery partitioning support bug - WHERE queries are not properly generated

Closes #HJ-116

### Description Of Changes

Update BigQuery to use parenthesis on the WHERE clause for SELECT queries.

### Code Changes

* [ ] Update `BigQueryQueryConfig.get_formatted_query_string` to surround the WHERE clause contents in parenthesis always.

### Steps to Confirm

* [ ] Run the test suite.

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
  * [ ] if there are any new client scopes created as part of the pull request, remember to update public-facing documentation that references our scope registry
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated
* If there are any database migrations:
  * [ ] Ensure that your downrev is up to date with the latest revision on `main`
  * [ ] Ensure that your `downgrade()` migration is correct and works
    * [ ] If a downgrade migration is not possible for this change, please call this out in the PR description!

2024-10-29 17:31 UTC, tvandort approved these changes

2024-10-29 18:39 UTC, NevilleS requested changes
@andres-torres-marroquin I don't see any tests here that also exercise the `partitioning` clauses. I'd like to be extra confident that we've tested how those get merged into the rest

2024-10-30 22:04 UTC, NevilleS commented
> > @andres-torres-marroquin I don't see any tests here that also exercise the `partitioning` clauses. I'd like to be extra confident that we've tested how those get merged into the rest
> 
> @NevilleS Actually this [test](https://github.com/ethyca/fides/blob/e37bd3f8ec1b8b4693509389da7546a557c3a1a4/tests/ops/service/connectors/test_bigquery_connector.py#L161) uses the `partitioning` clause, do you want me to add one that uses more than one identifying field? or a more explicit check?

Yes, I'd like to ensure there is an explicit test that shows the query we generate when there is a `partitioning` clause and multiple identities.

2024-10-31 17:38 UTC, NevilleS approved these changes
This looks good. The test feels awkward but that's non-blocking- maybe you can simplify that assertion...?

2024-10-31 17:38 UTC, NevilleS commented on tests/ops/service/connectors/test_bigquery_connector.py
> +                "SELECT address_id, created, custom_id, email, id, name FROM `silken-precinct-284918.fidesopstest.customer` WHERE (email = %(email)s OR custom_id = %(custom_id)s) AND (`created` > TIM
This looks good. It does feel awkward to be reading from the _logs_ for the assertion though...?

2024-10-31 17:38 UTC, NevilleS commented on tests/ops/service/connectors/test_bigquery_connector.py
> +        """Unit test of BigQueryQueryConfig.generate_delete specifically for a partitioned table with multiple identifying fields"""
nit:
```suggestion
        """Unit test of BigQueryConnection.retrieve_data specifically for a partitioned table with multiple identifying fields"""
```

2024-10-31 17:38 UTC, NevilleS commented on tests/fixtures/bigquery_fixtures.py
> +def bigquery_keyfile_creds():
👍 good reuse fixture

2024-10-31 17:38 UTC, NevilleS commented on CHANGELOG.md
> + - Fix BigQuery partitioning support bug - WHERE queries are not properly generated [#5432](https://github.com/ethyca/fides/pull/5432)
```suggestion
 - Fix BigQuery `partitioning` queries to properly support multiple identity clauses [#5432](https://github.com/ethyca/fides/pull/5432)
```

2024-10-31 19:52 UTC, merged