Gill/hj 71/migrate select inputs to ant
ethyca/fides pull request #5475
Opened 2024-11-07 16:39 UTC by gilluminate

Closes [HJ-169](https://ethyca.atlassian.net/browse/HJ-169)

### Description Of Changes

Migrating all of the "one-off" Select components to use the Ant Select component. There is more work to be done on the "custom" Select components, but that will come in another PR.

### Code Changes

* Select migration of select components (see what I did there?)
* Customized Taxonomy options
* Update Cypress tests with different element selectors
* New FilterSelect wrapper component for convenience to keep Filters consistent
* Updated layout of Dataset entry page to be stacked vertically instead of horizontally
* Replace language list from disabled Chakra Select with tags, to just use Ant tags (this was a hack since Chakra didn't have tags)

### Steps to Confirm

1.  _list any manual steps for reviewers to confirm the changes_

### Pre-Merge Checklist

* [ ] Issue requirements met
* [ ] All CI pipelines succeeded
* [ ] `CHANGELOG.md` updated
* Followup issues:
  * [ ] Followup issues created (include link)
  * [ ] No followup issues
* Database migrations:
  * [ ] Ensure that your downrev is up to date with the latest revision on `main`
  * [ ] Ensure that your `downgrade()` migration is correct and works
    * [ ] If a downgrade migration is not possible for this change, please call this out in the PR description!
  * [ ] No migrations
* Documentation:
  * [ ] Documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] Documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
  * [ ] If there are any new client scopes created as part of the pull request, remember to update public-facing documentation that references our scope registry
  * [ ] No documentation updates required

2024-11-12 23:21 UTC, jpople requested changes
Tested locally. Almost all working as intended:

* [x] "Select notice children" on privacy notices
* [x] Datamap report "export" file type
* [X] Consent automation notice selects
* [x] Datastore connection "dataset config"
* [x] Connection manager filters
* [x] System integrations dataset select
* [x] Messaging type
* [x] Privacy notice locations
* [x] Privacy notice language picker
* [x] Taxonomy select

I'm running into some bugs around the DictSuggestionSelects in the system form (tags, legal basis for profiling, legal basis for transfers, responsibility).  

On a clean form, they're populated with a blank tag instead of empty:

![Screenshot 2024-11-12 at 17 15 45](https://github.com/user-attachments/assets/6ef1910f-760d-40c7-bf61-a23d3226b210)

And are throwing errors when I try to change the value: 

https://github.com/user-attachments/assets/668d65bc-8646-411f-b3a4-5dc8cdcc7ba5

Also, for "tags", on main we have this "Create [tag name]..." to indicate that users are creating new tags, is it feasible to include something like that on Ant?  With just a blank select menu I think it's a little unclear how to use the field.

![Screenshot 2024-11-12 at 17 20 34](https://github.com/user-attachments/assets/b3e746d3-e702-4781-b6a8-421c024d5989)

2024-11-12 23:40 UTC, gilluminate commented
@jpople I think my latest commit solves those issues if you can pull latest. I'll investigate the "creating" question...

2024-11-13 00:10 UTC, gilluminate commented
@jpople it doesn't look like that option exists, but I created a feature request to see if they'll implement it for us https://github.com/ant-design/ant-design/issues/51600

2024-11-13 00:36 UTC, gilluminate commented
@jpople ok, I actually figured out how to get it working with the current options. Not as elegant as a new prop, but it works :)

2024-11-13 15:47 UTC, jpople commented on clients/admin-ui/src/features/system/dictionary-form/DictSuggestionInputs.tsx
> +                      return `Create "${searchValue}"`;
Nice workaround here!

2024-11-13 15:48 UTC, jpople approved these changes
Thanks for the changes-- looking good!

2024-11-14 18:58 UTC, Roger-Ethyca approved these changes
there will be some changes for E2E tests.

2024-11-15 21:15 UTC, merged