Data catalog UI: MVP
ethyca/fides pull request #5628
Opened 2024-12-20 04:33 UTC by jpople

Closes #<issue>

### Description Of Changes

_Write some things here about the changes and any potential caveats_

### Code Changes

* _list your code changes here_

### Steps to Confirm

1.  _list any manual steps for reviewers to confirm the changes_

### Pre-Merge Checklist

* [ ] Issue requirements met
* [ ] All CI pipelines succeeded
* [ ] `CHANGELOG.md` updated
* Followup issues:
  * [ ] Followup issues created (include link)
  * [ ] No followup issues
* Database migrations:
  * [ ] Ensure that your downrev is up to date with the latest revision on `main`
  * [ ] Ensure that your `downgrade()` migration is correct and works
    * [ ] If a downgrade migration is not possible for this change, please call this out in the PR description!
  * [ ] No migrations
* Documentation:
  * [ ] Documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] Documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
  * [ ] If there are any new client scopes created as part of the pull request, remember to update public-facing documentation that references our scope registry
  * [ ] No documentation updates required

2025-01-13 20:41 UTC, gilluminate requested changes
Overall looking good. Loving a lot of the abstractions for clean and more reusable code. Left a few comments, questions, and nit-picks for potential improvement.

2025-01-13 21:09 UTC, gilluminate commented on clients/admin-ui/src/features/data-discovery-and-detection/ClassificationCategoryBadge.tsx
> +        gap={1.5}
the alignment of the + button is off during testing, I think this `alignItems` and `gap` still belongs in the parent (probably both?)

2025-01-13 21:14 UTC, gilluminate commented on clients/admin-ui/src/pages/data-catalog/[systemId]/projects/[projectId].tsx
> +  }
Since this falls outside of the `Layout` the skeleton is taking up the entire page (bleeding edge to edge) which I don't think is the desired effect. This should probably be moved in lower.

2025-01-13 21:17 UTC, gilluminate reviewed
None of the breadcrumbs seem to be working properly. Clicking down in to a child level and then clicking a breadcrumb to go back just results in an empty table.

2025-01-13 23:11 UTC, jpople commented on clients/admin-ui/src/features/common/ResultStatusBadge.tsx
> +const ResultStatusBadge = React.forwardRef<HTMLSpanElement, BadgeProps>(
Good callout-- deleted this component and changed all of its uses to use the more generic BadgeCell.

2025-01-13 23:16 UTC, jpople commented on clients/admin-ui/src/features/common/dropdown/TaxonomySelect.tsx
> -import styles from "./TaxonomySelect.module.scss";
Probably I did something weird when merging in the changes from the previous taxonomy select rework.  I refactored this so it's used at this level again.

2025-01-13 23:20 UTC, jpople commented on clients/admin-ui/src/features/common/nav/v2/nav-config.ts
> +        scopes: [],
I've added a new flag for it for now-- ultimately this is intended to replace the existing D&D view.  Deployment strategy on this is also TBD, I think product wanted some time to test before it goes out to end users?

2025-01-13 23:23 UTC, jpople commented on clients/admin-ui/src/features/data-catalog/systems/EditDataUseCell.tsx
> +          width="100%"
Yeah, that definitely seems cleaner.

2025-01-13 23:26 UTC, jpople commented on clients/admin-ui/src/features/data-catalog/systems/EditMinimalDataUseModal.tsx
> +const EditMinimalDataUseModal = ({
This is intended to be a lighterweight version of the privacy declaration flow, which is why it allows adding with only a data use (previously categories were also required) and also why we have some of the more niche settings locked away in the "advanced" section.  "Minimal" seemed clear to me but I could also change it to be more contextual like CatalogEditDataUseModal or something.

2025-01-14 00:00 UTC, gilluminate commented on clients/admin-ui/src/features/data-catalog/systems/EditMinimalDataUseModal.tsx
> +const EditMinimalDataUseModal = ({
Ah okay that makes sense. I wouldn't change the name. Thanks for clarifying.

2025-01-14 16:28 UTC, gilluminate commented on clients/admin-ui/src/features/data-catalog/projects/CatalogProjectsTable.tsx
> +  if (isLoading || isFetching) {
I would suggest only using `isLoading` here so the skeleton appears on initial load, but not every time a new Data Use is added.

2025-01-14 16:44 UTC, gilluminate approved these changes
A few nitpicks, but overall looking great.

2025-01-29 16:49 UTC, merged