Copy over Admin UI base for ctl-admin-ui
ethyca/fides pull request #624
Opened 2022-05-10 15:41 UTC by elliotbonneville

### Code Changes

* [x] Create a `clients` directory
* [x] Create an `admin-ui` directory containing copied over directory from `admin-ui`
* [x] Remove Admin UI specific features from `admin-ui` and clean up

### Steps to Confirm

* [ ] _list any manual steps taken to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

2022-05-10 15:53 UTC, allisonking approved these changes
woot, lgtm! would just want to double check with @ThomasLaPiana that this code lives in the right folder (`src/clients/ctl-admin-ui`)

2022-05-11 14:28 UTC, ThomasLaPiana commented on src/clients/ctl-admin-ui/__tests__/index.test.tsx
> +import { render, screen } from '@testing-library/react';
> woot, lgtm! would just want to double check with @ThomasLaPiana that this code lives in the right folder (`src/clients/ctl-admin-ui`)

I don't have any strong opinions here as long as everything is logically organized 😄

2022-05-11 14:28 UTC, ThomasLaPiana commented
> woot, lgtm! would just want to double check with @ThomasLaPiana that this code lives in the right folder (`src/clients/ctl-admin-ui`)

I don't have any strong opinions here as long as everything is logically organized 😄  @allisonking

2022-05-11 14:28 UTC, ThomasLaPiana commented
> woot, lgtm! would just want to double check with @ThomasLaPiana that this code lives in the right folder (`src/clients/ctl-admin-ui`)

I don't have any strong opinions here as long as everything is logically organized 😄  @allisonking

2022-05-11 14:31 UTC, NevilleS commented
This is super nitpicky, but can we use `admin-ui` instead of `ctl-admin-ui`?

It's just a bit inconsistent across projects to call it `admin-ui` on fidesops, but `ctl-admin-ui` on fidesctl, you know?

2022-05-11 14:34 UTC, ThomasLaPiana commented on src/clients/ctl-admin-ui/.env.development
> +NEXT_PUBLIC_FIDESOPS_API=http://0.0.0.0:8080/api/v1
```suggestion
NEXT_PUBLIC_FIDESCTL_API=http://0.0.0.0:8080/api/v1
```

2022-05-11 20:43 UTC, allisonking commented
Does anyone know where I can get an svg of the fidesctl logo to replace the fidesops one?

2022-05-11 20:48 UTC, elliotbonneville commented on src/clients/ctl-admin-ui/src/features/common/Icon/ArrowDownLine.tsx
> +  d: 'M12 13.1719L16.95 8.22192L18.364 9.63592L12 15.9999L5.63599 9.63592L7.04999 8.22192L12 13.1719Z',
I navigated to the appropriate SVG element in Figma, then right clicked it and clicked "Copy as SVG".

2022-05-11 20:49 UTC, elliotbonneville commented
@allisonking See my other recent comment.

@NevilleS Agreed re. name. Also, for further nitpicky consistency I noticed that `admin-ui` lives in `fidesops/clients` but this directory would be `fides/src/clients`. We should either move `fidesops/clients` to `fidesops/src/clients` or `fides/src/clients/ctx-admin-ui` to `fides/clients/admin-ui`. Thoughts, all?

2022-05-11 20:50 UTC, elliotbonneville commented on src/clients/ctl-admin-ui/src/features/common/Icon/ArrowDownLine.tsx
> +  d: 'M12 13.1719L16.95 8.22192L18.364 9.63592L12 15.9999L5.63599 9.63592L7.04999 8.22192L12 13.1719Z',
(That gave me the body of the SVG, which I then copied into the `d` param of the Chakra icon creation options object).

2022-05-11 21:05 UTC, allisonking commented on src/clients/ctl-admin-ui/src/features/common/Icon/ArrowDownLine.tsx
> +  d: 'M12 13.1719L16.95 8.22192L18.364 9.63592L12 15.9999L5.63599 9.63592L7.04999 8.22192L12 13.1719Z',
beautiful, thank you!

2022-05-13 15:23 UTC, ThomasLaPiana requested changes
`internal` shouldn't get committed in the `fidesctl.toml`

2022-05-13 17:02 UTC, allisonking commented
> @elliotbonneville easier for us to match fidesops than change fidesops I think. Let's go ahead and match and then ship it!

okay, I can change and clean up the toml at the same time

2022-05-13 21:28 UTC, ThomasLaPiana approved these changes
Ship it!

2022-05-16 20:01 UTC, merged