Add push command to replace apply
ethyca/fides pull request #943
Opened 2022-07-26 21:02 UTC by earmenda

Closes #923 

### Code Changes

* [ ] _list your code changes here_

### Steps to Confirm

* [ ] _list any manual steps taken to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

_Write some things here about the changes and any potential caveats_

2022-07-26 21:20 UTC, earmenda commented
I tried doing this in a way where the `push` function just calls the cli `apply` function but it doesn't work like i expected. For now just calling the same code paths by copying what the `apply` command does. 

Still need to update documentation. We could also rename the `apply.py` file and any references to `apply` to push internally. Thoughts?

2022-07-27 03:45 UTC, SteveDMurphy approved these changes
I like this as an efficient way to start breaking down the `apply` command, nice work @earmenda !! 

Would it make sense to try and give a version estimate of when it will be fully pulled (i.e. `1.9`)? I can imagine there are a lot of docs updates as well so am assuming those might go in a follow on issue 👍🏽

2022-07-27 11:48 UTC, ThomasLaPiana commented on src/fidesctl/cli/commands/core.py
> +@click.command(deprecated=True)
hey that's pretty neat 💯

2022-07-27 11:50 UTC, ThomasLaPiana commented on src/fidesctl/cli/commands/core.py
> +def push(ctx: click.Context, dry: bool, diff: bool, manifests_dir: str) -> None:
is it possible to duplicate the command without a copy/pasta? I haven't tried it but I was hoping there'd be a clever way to do that, if not its fine, this command doesn't change much!

2022-07-27 11:50 UTC, ThomasLaPiana requested changes
As this is a deprecation, lets go ahead and make the docs updates here too

2022-07-27 11:51 UTC, ThomasLaPiana commented
@conceptualshark would you be able to help us update the docs here to replace `fidesctl apply` with `fidesctl push` where needed? 🙏

2022-07-27 11:54 UTC, ThomasLaPiana commented on src/fidesctl/cli/commands/core.py
> +def push(ctx: click.Context, dry: bool, diff: bool, manifests_dir: str) -> None:
after looking into some of the solutions you mentioned, it's not worth the eng time to figure this out before the deprecation, I'm good with how it is 👍

2022-07-27 11:55 UTC, ThomasLaPiana commented
@earmenda as an additional point of consistency, let's also update the logging to say `PUSHED 1 <resource>...` as opposed to `APPLIED 1 <resource>...`

2022-07-27 14:20 UTC, conceptualshark commented
👍 think that's all the `apply` uses updated, should be good to go!

2022-07-28 00:31 UTC, ThomasLaPiana commented
@earmenda I'm making a few more cleanup changes here and then i'll merge

2022-07-28 01:48 UTC, earmenda commented
thanks @ThomasLaPiana

2022-07-28 01:51 UTC, ThomasLaPiana approved these changes

2022-07-28 04:25 UTC, merged