Bump Python version to 3.9 in Docker and setup.py
ethyca/fides pull request #974
Opened 2022-08-09 08:38 UTC by ThomasLaPiana

Closes #973 

### Code Changes

* [ ] update the dockerfile
* [ ] update `setup.py`

### Steps to Confirm

* [ ] _list any manual steps taken to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

_Write some things here about the changes and any potential caveats_

2022-08-09 11:00 UTC, sanders41 requested changes

2022-08-09 11:00 UTC, sanders41 commented on setup.py
> +        "Programming Language :: Python :: 3.11",
I just tested and some of the binary dependencies we are using haven't been built for 3.11 yet and error on `pip install`. Based on some of my initial testing with 3.11 I'm confident all of the fidesctl code itself will work, we just need to wait for binaries to be available to say we support it.

```suggestion
````

2022-08-10 05:02 UTC, ThomasLaPiana commented
@sanders41 great catches! Thanks for the review 🙂

2022-08-10 06:49 UTC, sanders41 approved these changes

2022-08-10 06:58 UTC, merged